# Generated by Django 4.2.5 on 2023-09-28 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Currencies',
        ),
    ]
